# Generated by Django 5.2.1 on 2025-07-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='image',
            field=models.ImageField(upload_to='greenhouse_images/'),
        ),
    ]
